//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.Services.UserContextService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ntreev.com", ConfigurationName="UserContextService.IUserContextService", CallbackContract=typeof(Ntreev.Crema.Services.UserContextService.IUserContextServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    internal interface IUserContextService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IUserContextService/Subscribe", ReplyAction="http://www.ntreev.com/IUserContextService/SubscribeResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.UserContextMetaData> Subscribe(string userID, byte[] password, string version, string platformID, string culture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IUserContextService/Unsubscribe", ReplyAction="http://www.ntreev.com/IUserContextService/UnsubscribeResponse")]
        Ntreev.Crema.ServiceModel.ResultBase Unsubscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IUserContextService/Shutdown", ReplyAction="http://www.ntreev.com/IUserContextService/ShutdownResponse")]
        Ntreev.Crema.ServiceModel.ResultBase Shutdown(int milliseconds, Ntreev.Crema.ServiceModel.ShutdownType shutdownType, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IUserContextService/CancelShutdown", ReplyAction="http://www.ntreev.com/IUserContextService/CancelShutdownResponse")]
        Ntreev.Crema.ServiceModel.ResultBase CancelShutdown();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IUserContextService/NewUser", ReplyAction="http://www.ntreev.com/IUserContextService/NewUserResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.UserInfo> NewUser(string userID, string categoryPath, byte[] password, string userName, Ntreev.Crema.ServiceModel.Authority authority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IUserContextService/NewUserCategory", ReplyAction="http://www.ntreev.com/IUserContextService/NewUserCategoryResponse")]
        Ntreev.Crema.ServiceModel.ResultBase NewUserCategory(string categoryPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IUserContextService/RenameUserItem", ReplyAction="http://www.ntreev.com/IUserContextService/RenameUserItemResponse")]
        Ntreev.Crema.ServiceModel.ResultBase RenameUserItem(string itemPath, string newName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IUserContextService/MoveUserItem", ReplyAction="http://www.ntreev.com/IUserContextService/MoveUserItemResponse")]
        Ntreev.Crema.ServiceModel.ResultBase MoveUserItem(string itemPath, string parentPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IUserContextService/DeleteUserItem", ReplyAction="http://www.ntreev.com/IUserContextService/DeleteUserItemResponse")]
        Ntreev.Crema.ServiceModel.ResultBase DeleteUserItem(string itemPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IUserContextService/ChangeUserInfo", ReplyAction="http://www.ntreev.com/IUserContextService/ChangeUserInfoResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.UserInfo> ChangeUserInfo(string userID, byte[] password, byte[] newPassword, string userName, System.Nullable<Ntreev.Crema.ServiceModel.Authority> authority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IUserContextService/Kick", ReplyAction="http://www.ntreev.com/IUserContextService/KickResponse")]
        Ntreev.Crema.ServiceModel.ResultBase Kick(string userID, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IUserContextService/Ban", ReplyAction="http://www.ntreev.com/IUserContextService/BanResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.BanInfo> Ban(string userID, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IUserContextService/Unban", ReplyAction="http://www.ntreev.com/IUserContextService/UnbanResponse")]
        Ntreev.Crema.ServiceModel.ResultBase Unban(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IUserContextService/SendMessage", ReplyAction="http://www.ntreev.com/IUserContextService/SendMessageResponse")]
        Ntreev.Crema.ServiceModel.ResultBase SendMessage(string userID, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IUserContextService/NotifyMessage", ReplyAction="http://www.ntreev.com/IUserContextService/NotifyMessageResponse")]
        Ntreev.Crema.ServiceModel.ResultBase NotifyMessage(string[] userIDs, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IUserContextService/IsAlive", ReplyAction="http://www.ntreev.com/IUserContextService/IsAliveResponse")]
        bool IsAlive();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IUserContextServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IUserContextService/OnServiceClosed")]
        void OnServiceClosed(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, Ntreev.Crema.ServiceModel.CloseInfo closeInfo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IUserContextService/OnUsersChanged")]
        void OnUsersChanged(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, Ntreev.Crema.ServiceModel.UserInfo[] userInfos);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IUserContextService/OnUsersStateChanged")]
        void OnUsersStateChanged(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, string[] userIDs, Ntreev.Crema.ServiceModel.UserState[] states);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IUserContextService/OnUserItemsCreated")]
        void OnUserItemsCreated(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, string[] itemPaths, System.Nullable<Ntreev.Crema.ServiceModel.UserInfo>[] args);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IUserContextService/OnUserItemsRenamed")]
        void OnUserItemsRenamed(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, string[] itemPaths, string[] newNames);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IUserContextService/OnUserItemsMoved")]
        void OnUserItemsMoved(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, string[] itemPaths, string[] parentPaths);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IUserContextService/OnUserItemsDeleted")]
        void OnUserItemsDeleted(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, string[] itemPaths);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IUserContextService/OnUsersLoggedIn")]
        void OnUsersLoggedIn(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, string[] userIDs);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IUserContextService/OnUsersLoggedOut")]
        void OnUsersLoggedOut(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, string[] userIDs, Ntreev.Crema.ServiceModel.CloseInfo closeInfo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IUserContextService/OnUsersKicked")]
        void OnUsersKicked(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, string[] userIDs, string[] comments);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IUserContextService/OnUsersBanChanged")]
        void OnUsersBanChanged(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, Ntreev.Crema.ServiceModel.BanInfo[] banInfos, Ntreev.Crema.ServiceModel.BanChangeType changeType, string[] comments);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IUserContextService/OnMessageReceived")]
        void OnMessageReceived(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, string[] userIDs, string message, Ntreev.Crema.ServiceModel.MessageType messageType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IUserContextServiceChannel : Ntreev.Crema.Services.UserContextService.IUserContextService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class UserContextServiceClient : System.ServiceModel.DuplexClientBase<Ntreev.Crema.Services.UserContextService.IUserContextService>, Ntreev.Crema.Services.UserContextService.IUserContextService {
        
        public UserContextServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public UserContextServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public UserContextServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UserContextServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UserContextServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.UserContextMetaData> Subscribe(string userID, byte[] password, string version, string platformID, string culture) {
            return base.Channel.Subscribe(userID, password, version, platformID, culture);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase Unsubscribe() {
            return base.Channel.Unsubscribe();
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase Shutdown(int milliseconds, Ntreev.Crema.ServiceModel.ShutdownType shutdownType, string message) {
            return base.Channel.Shutdown(milliseconds, shutdownType, message);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase CancelShutdown() {
            return base.Channel.CancelShutdown();
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.UserInfo> NewUser(string userID, string categoryPath, byte[] password, string userName, Ntreev.Crema.ServiceModel.Authority authority) {
            return base.Channel.NewUser(userID, categoryPath, password, userName, authority);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase NewUserCategory(string categoryPath) {
            return base.Channel.NewUserCategory(categoryPath);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase RenameUserItem(string itemPath, string newName) {
            return base.Channel.RenameUserItem(itemPath, newName);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase MoveUserItem(string itemPath, string parentPath) {
            return base.Channel.MoveUserItem(itemPath, parentPath);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase DeleteUserItem(string itemPath) {
            return base.Channel.DeleteUserItem(itemPath);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.UserInfo> ChangeUserInfo(string userID, byte[] password, byte[] newPassword, string userName, System.Nullable<Ntreev.Crema.ServiceModel.Authority> authority) {
            return base.Channel.ChangeUserInfo(userID, password, newPassword, userName, authority);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase Kick(string userID, string comment) {
            return base.Channel.Kick(userID, comment);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.BanInfo> Ban(string userID, string comment) {
            return base.Channel.Ban(userID, comment);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase Unban(string userID) {
            return base.Channel.Unban(userID);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase SendMessage(string userID, string message) {
            return base.Channel.SendMessage(userID, message);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase NotifyMessage(string[] userIDs, string message) {
            return base.Channel.NotifyMessage(userIDs, message);
        }
        
        public bool IsAlive() {
            return base.Channel.IsAlive();
        }
    }
}
