//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.Services.DomainContextService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ntreev.com", ConfigurationName="DomainContextService.IDomainContextService", CallbackContract=typeof(Ntreev.Crema.Services.DomainContextService.IDomainContextServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    internal interface IDomainContextService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDomainContextService/Subscribe", ReplyAction="http://www.ntreev.com/IDomainContextService/SubscribeResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainContextMetaData> Subscribe(System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDomainContextService/Unsubscribe", ReplyAction="http://www.ntreev.com/IDomainContextService/UnsubscribeResponse")]
        Ntreev.Crema.ServiceModel.ResultBase Unsubscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDomainContextService/GetMetaData", ReplyAction="http://www.ntreev.com/IDomainContextService/GetMetaDataResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainMetaData[]> GetMetaData(System.Guid dataBaseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDomainContextService/SetUserLocation", ReplyAction="http://www.ntreev.com/IDomainContextService/SetUserLocationResponse")]
        Ntreev.Crema.ServiceModel.ResultBase SetUserLocation(System.Guid domainID, Ntreev.Crema.ServiceModel.DomainLocationInfo location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDomainContextService/NewRow", ReplyAction="http://www.ntreev.com/IDomainContextService/NewRowResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainRowInfo[]> NewRow(System.Guid domainID, Ntreev.Crema.ServiceModel.DomainRowInfo[] rows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDomainContextService/RemoveRow", ReplyAction="http://www.ntreev.com/IDomainContextService/RemoveRowResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainRowInfo[]> RemoveRow(System.Guid domainID, Ntreev.Crema.ServiceModel.DomainRowInfo[] rows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDomainContextService/SetRow", ReplyAction="http://www.ntreev.com/IDomainContextService/SetRowResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainRowInfo[]> SetRow(System.Guid domainID, Ntreev.Crema.ServiceModel.DomainRowInfo[] rows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDomainContextService/SetProperty", ReplyAction="http://www.ntreev.com/IDomainContextService/SetPropertyResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainContextMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.CremaFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Library.SignatureDate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainContextMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainState))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainUserMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainUserMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainLocationInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainFieldInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainFieldInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainUserInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainAccessType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainUserState))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainMetaData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainRowInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainRowInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainRowInfo[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TableInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.ColumnInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.ColumnInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Library.TagInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TableInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TypeInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TypeMemberInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TypeMemberInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TypeInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.CallbackInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.CloseInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.CloseReason))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.RemoveInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.RemoveReason))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Guid[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bool[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        Ntreev.Crema.ServiceModel.ResultBase SetProperty(System.Guid domainID, string propertyName, object value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDomainContextService/BeginUserEdit", ReplyAction="http://www.ntreev.com/IDomainContextService/BeginUserEditResponse")]
        Ntreev.Crema.ServiceModel.ResultBase BeginUserEdit(System.Guid domainID, Ntreev.Crema.ServiceModel.DomainLocationInfo location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDomainContextService/EndUserEdit", ReplyAction="http://www.ntreev.com/IDomainContextService/EndUserEditResponse")]
        Ntreev.Crema.ServiceModel.ResultBase EndUserEdit(System.Guid domainID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDomainContextService/Kick", ReplyAction="http://www.ntreev.com/IDomainContextService/KickResponse")]
        Ntreev.Crema.ServiceModel.ResultBase Kick(System.Guid domainID, string userID, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDomainContextService/SetOwner", ReplyAction="http://www.ntreev.com/IDomainContextService/SetOwnerResponse")]
        Ntreev.Crema.ServiceModel.ResultBase SetOwner(System.Guid domainID, string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDomainContextService/DeleteDomain", ReplyAction="http://www.ntreev.com/IDomainContextService/DeleteDomainResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainContextMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.CremaFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Library.SignatureDate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainContextMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainState))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainUserMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainUserMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainLocationInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainFieldInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainFieldInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainUserInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainAccessType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainUserState))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainMetaData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainRowInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainRowInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainRowInfo[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TableInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.ColumnInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.ColumnInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Library.TagInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TableInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TypeInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TypeMemberInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TypeMemberInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TypeInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.CallbackInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.CloseInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.CloseReason))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.RemoveInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.RemoveReason))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Guid[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bool[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        Ntreev.Crema.ServiceModel.ResultBase<object> DeleteDomain(System.Guid domainID, bool force);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDomainContextService/IsAlive", ReplyAction="http://www.ntreev.com/IDomainContextService/IsAliveResponse")]
        bool IsAlive();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IDomainContextServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDomainContextService/OnServiceClosed")]
        void OnServiceClosed(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, Ntreev.Crema.ServiceModel.CloseInfo closeInfo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDomainContextService/OnDomainsCreated")]
        void OnDomainsCreated(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, Ntreev.Crema.ServiceModel.DomainMetaData[] metaDatas);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDomainContextService/OnDomainsDeleted")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainContextMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.CremaFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Library.SignatureDate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainContextMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainState))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainUserMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainUserMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainLocationInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainFieldInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainFieldInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainUserInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainAccessType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainUserState))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainMetaData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainRowInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainRowInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainRowInfo[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TableInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.ColumnInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.ColumnInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Library.TagInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TableInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TypeInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TypeMemberInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TypeMemberInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TypeInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.CallbackInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.CloseInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.CloseReason))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.RemoveInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.RemoveReason))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Guid[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bool[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void OnDomainsDeleted(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, System.Guid[] domainIDs, bool[] IsCanceleds, object[] results);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDomainContextService/OnDomainInfoChanged")]
        void OnDomainInfoChanged(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, System.Guid domainID, Ntreev.Crema.ServiceModel.DomainInfo domainInfo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDomainContextService/OnDomainStateChanged")]
        void OnDomainStateChanged(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, System.Guid domainID, Ntreev.Crema.ServiceModel.DomainState domainState);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDomainContextService/OnUserAdded")]
        void OnUserAdded(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, System.Guid domainID, Ntreev.Crema.ServiceModel.DomainUserInfo domainUserInfo, Ntreev.Crema.ServiceModel.DomainUserState domainUserState, byte[] data, System.Guid taskID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDomainContextService/OnUserRemoved")]
        void OnUserRemoved(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, System.Guid domainID, string userID, string ownerID, Ntreev.Crema.ServiceModel.RemoveInfo removeInfo, System.Guid taskID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDomainContextService/OnUserLocationChanged")]
        void OnUserLocationChanged(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, System.Guid domainID, Ntreev.Crema.ServiceModel.DomainLocationInfo domainLocationInfo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDomainContextService/OnUserStateChanged")]
        void OnUserStateChanged(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, System.Guid domainID, Ntreev.Crema.ServiceModel.DomainUserState domainUserState);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDomainContextService/OnUserEditBegun")]
        void OnUserEditBegun(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, System.Guid domainID, Ntreev.Crema.ServiceModel.DomainLocationInfo domainLocationInfo, System.Guid taskID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDomainContextService/OnUserEditEnded")]
        void OnUserEditEnded(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, System.Guid domainID, System.Guid taskID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDomainContextService/OnOwnerChanged")]
        void OnOwnerChanged(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, System.Guid domainID, string ownerID, System.Guid taskID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDomainContextService/OnRowAdded")]
        void OnRowAdded(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, System.Guid domainID, Ntreev.Crema.ServiceModel.DomainRowInfo[] rows, System.Guid taskID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDomainContextService/OnRowChanged")]
        void OnRowChanged(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, System.Guid domainID, Ntreev.Crema.ServiceModel.DomainRowInfo[] rows, System.Guid taskID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDomainContextService/OnRowRemoved")]
        void OnRowRemoved(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, System.Guid domainID, Ntreev.Crema.ServiceModel.DomainRowInfo[] rows, System.Guid taskID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDomainContextService/OnPropertyChanged")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DBNull))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainContextMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.CremaFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Library.SignatureDate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainContextMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainState))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainUserMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainUserMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainLocationInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainFieldInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainFieldInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainUserInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainAccessType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainUserState))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainMetaData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainRowInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.DomainRowInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainRowInfo[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TableInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.ColumnInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.ColumnInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Library.TagInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TableInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TypeInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TypeMemberInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TypeMemberInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.Data.TypeInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.ResultBase<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.CallbackInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.CloseInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.CloseReason))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.RemoveInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ntreev.Crema.ServiceModel.RemoveReason))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Guid[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bool[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void OnPropertyChanged(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, System.Guid domainID, string propertyName, object value, System.Guid taskID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDomainContextService/OnTaskCompleted")]
        void OnTaskCompleted(Ntreev.Crema.ServiceModel.CallbackInfo callbackInfo, System.Guid[] taskIDs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IDomainContextServiceChannel : Ntreev.Crema.Services.DomainContextService.IDomainContextService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class DomainContextServiceClient : System.ServiceModel.DuplexClientBase<Ntreev.Crema.Services.DomainContextService.IDomainContextService>, Ntreev.Crema.Services.DomainContextService.IDomainContextService {
        
        public DomainContextServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public DomainContextServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public DomainContextServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DomainContextServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DomainContextServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainContextMetaData> Subscribe(System.Guid authenticationToken) {
            return base.Channel.Subscribe(authenticationToken);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase Unsubscribe() {
            return base.Channel.Unsubscribe();
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainMetaData[]> GetMetaData(System.Guid dataBaseID) {
            return base.Channel.GetMetaData(dataBaseID);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase SetUserLocation(System.Guid domainID, Ntreev.Crema.ServiceModel.DomainLocationInfo location) {
            return base.Channel.SetUserLocation(domainID, location);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainRowInfo[]> NewRow(System.Guid domainID, Ntreev.Crema.ServiceModel.DomainRowInfo[] rows) {
            return base.Channel.NewRow(domainID, rows);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainRowInfo[]> RemoveRow(System.Guid domainID, Ntreev.Crema.ServiceModel.DomainRowInfo[] rows) {
            return base.Channel.RemoveRow(domainID, rows);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DomainRowInfo[]> SetRow(System.Guid domainID, Ntreev.Crema.ServiceModel.DomainRowInfo[] rows) {
            return base.Channel.SetRow(domainID, rows);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase SetProperty(System.Guid domainID, string propertyName, object value) {
            return base.Channel.SetProperty(domainID, propertyName, value);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase BeginUserEdit(System.Guid domainID, Ntreev.Crema.ServiceModel.DomainLocationInfo location) {
            return base.Channel.BeginUserEdit(domainID, location);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase EndUserEdit(System.Guid domainID) {
            return base.Channel.EndUserEdit(domainID);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase Kick(System.Guid domainID, string userID, string comment) {
            return base.Channel.Kick(domainID, userID, comment);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase SetOwner(System.Guid domainID, string userID) {
            return base.Channel.SetOwner(domainID, userID);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<object> DeleteDomain(System.Guid domainID, bool force) {
            return base.Channel.DeleteDomain(domainID, force);
        }
        
        public bool IsAlive() {
            return base.Channel.IsAlive();
        }
    }
}
